"""Align application schema

Revision ID: 0346aeed357c
Revises: 267306801b2d
Create Date: 2026-09-22 03:06:43.592087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0346aeed357c'
down_revision: Union[str, Sequence[str], None] = '267306801b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'application_status_history',
        sa.Column('changed_by', sa.Uuid(), nullable=False),
    )

    op.create_foreign_key(
        op.f('fk_application_status_history_changed_by_users'),
        'application_status_history',
        'users',
        ['changed_by'],
        ['id'],
    )

    op.add_column(
        'applications',
        sa.Column('reason_for_adoption', sa.Text(), nullable=False),
    )

    op.add_column(
        'applications',
        sa.Column('care_plan', sa.Text(), nullable=False),
    )

    op.add_column(
        'applications',
        sa.Column('additional_information', sa.Text(), nullable=True),
    )

    op.add_column(
        'applications',
        sa.Column(
            'home_type',
            postgresql.ENUM(
                'APARTMENT',
                'HOUSE',
                name='home_type',
                create_type=False,
            ),
            nullable=False,
        ),
    )

    op.add_column(
        'applications',
        sa.Column(
            'outdoor_space',
            postgresql.ENUM(
                'NONE',
                'LIMITED',
                'AVAILABLE',
                name='outdoor_space',
                create_type=False,
            ),
            nullable=False,
        ),
    )

    op.add_column(
        'applications',
        sa.Column(
            'activity_level',
            postgresql.ENUM(
                'LOW',
                'MEDIUM',
                'HIGH',
                name='activity_level',
                create_type=False,
            ),
            nullable=False,
        ),
    )

    op.add_column(
        'applications',
        sa.Column('children_in_household', sa.Boolean(), nullable=False),
    )

    op.add_column(
        'applications',
        sa.Column('existing_dogs', sa.Boolean(), nullable=False),
    )

    op.add_column(
        'applications',
        sa.Column('existing_cats', sa.Boolean(), nullable=False),
    )

    op.add_column(
        'applications',
        sa.Column(
            'experience_level',
            postgresql.ENUM(
                'FIRST_TIME',
                'SOME_EXPERIENCE',
                'EXPERIENCED',
                name='experience_level',
                create_type=False,
            ),
            nullable=False,
        ),
    )

    op.add_column(
        'applications',
        sa.Column(
            'time_available',
            postgresql.ENUM(
                'LESS_THAN_1_HOUR',
                'ONE_TO_TWO_HOURS',
                'TWO_TO_FOUR_HOURS',
                'FOUR_PLUS_HOURS',
                name='time_available',
                create_type=False,
            ),
            nullable=False,
        ),
    )

    op.create_index(
        'uq_applications_one_active_per_adopter_animal',
        'applications',
        ['adopter_profile_id', 'animal_id'],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('SUBMITTED', 'UNDER_REVIEW', 'HOME_CHECK', 'APPROVED')"
        ),
    )

    op.drop_column('applications', 'applicant_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'applications',
        sa.Column(
            'applicant_message',
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.drop_index(
        'uq_applications_one_active_per_adopter_animal',
        table_name='applications',
        postgresql_where=sa.text(
            "status IN ('SUBMITTED', 'UNDER_REVIEW', 'HOME_CHECK', 'APPROVED')"
        ),
    )

    op.drop_column('applications', 'time_available')
    op.drop_column('applications', 'experience_level')
    op.drop_column('applications', 'existing_cats')
    op.drop_column('applications', 'existing_dogs')
    op.drop_column('applications', 'children_in_household')
    op.drop_column('applications', 'activity_level')
    op.drop_column('applications', 'outdoor_space')
    op.drop_column('applications', 'home_type')
    op.drop_column('applications', 'additional_information')
    op.drop_column('applications', 'care_plan')
    op.drop_column('applications', 'reason_for_adoption')

    op.drop_constraint(
        op.f('fk_application_status_history_changed_by_users'),
        'application_status_history',
        type_='foreignkey',
    )

    op.drop_column('application_status_history', 'changed_by')
    # ### end Alembic commands ###