"""Create initial database schema

Revision ID: 267306801b2d
Revises: 
Create Date: 2026-09-20 02:12:56.793915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267306801b2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality_traits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personality_traits')),
    sa.UniqueConstraint('name', name=op.f('uq_personality_traits_name'))
    )
    op.create_table('rescue_organisations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rescue_organisations'))
    )
    op.create_table('facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['rescue_organisations.id'], name=op.f('fk_facilities_organisation_id_rescue_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    op.create_table('organisation_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('ADOPTER', 'RESCUE_STAFF', name='user_role'), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['rescue_organisations.id'], name=op.f('fk_organisation_invitations_organisation_id_rescue_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_organisation_invitations_token_hash'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADOPTER', 'RESCUE_STAFF', name='user_role'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', name='account_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(role = 'ADOPTER' AND organisation_id IS NULL) OR (role = 'RESCUE_STAFF' AND organisation_id IS NOT NULL)", name='ck_users_role_organisation'),
    sa.ForeignKeyConstraint(['organisation_id'], ['rescue_organisations.id'], name=op.f('fk_users_organisation_id_rescue_organisations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('adopter_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('home_type', sa.Enum('APARTMENT', 'HOUSE', name='home_type'), nullable=False),
    sa.Column('outdoor_space', sa.Enum('NONE', 'LIMITED', 'AVAILABLE', name='outdoor_space'), nullable=False),
    sa.Column('activity_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='activity_level'), nullable=False),
    sa.Column('children_in_household', sa.Boolean(), nullable=False),
    sa.Column('existing_dogs', sa.Boolean(), nullable=False),
    sa.Column('existing_cats', sa.Boolean(), nullable=False),
    sa.Column('experience_level', sa.Enum('FIRST_TIME', 'SOME_EXPERIENCE', 'EXPERIENCED', name='experience_level'), nullable=False),
    sa.Column('time_available', sa.Enum('LESS_THAN_1_HOUR', 'ONE_TO_TWO_HOURS', 'TWO_TO_FOUR_HOURS', 'FOUR_PLUS_HOURS', name='time_available'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_adopter_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adopter_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_adopter_profiles_user_id'))
    )
    op.create_table('animals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', name='species'), nullable=False),
    sa.Column('age_value', sa.Integer(), nullable=False),
    sa.Column('age_unit', sa.Enum('WEEKS', 'MONTHS', 'YEARS', name='age_unit'), nullable=False),
    sa.Column('age_recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='size'), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('energy_level', sa.Enum('UNKNOWN', 'LOW', 'MEDIUM', 'HIGH', name='energy_level'), nullable=False),
    sa.Column('personality_description', sa.Text(), nullable=True),
    sa.Column('children_compatibility', sa.Enum('UNKNOWN', 'COMPATIBLE', 'NOT_COMPATIBLE', name='compatibility'), nullable=False),
    sa.Column('dog_compatibility', sa.Enum('UNKNOWN', 'COMPATIBLE', 'NOT_COMPATIBLE', name='compatibility'), nullable=False),
    sa.Column('cat_compatibility', sa.Enum('UNKNOWN', 'COMPATIBLE', 'NOT_COMPATIBLE', name='compatibility'), nullable=False),
    sa.Column('suitable_home_type', sa.Enum('UNKNOWN', 'APARTMENT', 'HOUSE', 'EITHER', name='suitable_home_type'), nullable=False),
    sa.Column('outdoor_space_requirement', sa.Enum('UNKNOWN', 'NOT_REQUIRED', 'PREFERRED', 'REQUIRED', name='outdoor_space_requirement'), nullable=False),
    sa.Column('experience_requirement', sa.Enum('UNKNOWN', 'NO_EXPERIENCE_REQUIRED', 'SOME_EXPERIENCE_PREFERRED', 'EXPERIENCED_OWNER_REQUIRED', name='experience_requirement'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ADOPTION_PENDING', 'ADOPTED', 'UNAVAILABLE', name='animal_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age_value >= 0', name='ck_animals_age_value_non_negative'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_animals_facility_id_facilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animals'))
    )
    op.create_table('adopter_child_age_groups',
    sa.Column('adopter_profile_id', sa.Uuid(), nullable=False),
    sa.Column('child_age_group', sa.Enum('YOUNG_CHILDREN', 'SCHOOL_AGE_CHILDREN', 'TEENAGERS', name='child_age_group'), nullable=False),
    sa.ForeignKeyConstraint(['adopter_profile_id'], ['adopter_profiles.id'], name=op.f('fk_adopter_child_age_groups_adopter_profile_id_adopter_profiles')),
    sa.PrimaryKeyConstraint('adopter_profile_id', 'child_age_group', name=op.f('pk_adopter_child_age_groups'))
    )
    op.create_table('adopter_preferred_sizes',
    sa.Column('adopter_profile_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='size'), nullable=False),
    sa.ForeignKeyConstraint(['adopter_profile_id'], ['adopter_profiles.id'], name=op.f('fk_adopter_preferred_sizes_adopter_profile_id_adopter_profiles')),
    sa.PrimaryKeyConstraint('adopter_profile_id', 'size', name=op.f('pk_adopter_preferred_sizes'))
    )
    op.create_table('adopter_preferred_species',
    sa.Column('adopter_profile_id', sa.Uuid(), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', name='species'), nullable=False),
    sa.ForeignKeyConstraint(['adopter_profile_id'], ['adopter_profiles.id'], name=op.f('fk_adopter_preferred_species_adopter_profile_id_adopter_profiles')),
    sa.PrimaryKeyConstraint('adopter_profile_id', 'species', name=op.f('pk_adopter_preferred_species'))
    )
    op.create_table('animal_personality_traits',
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('personality_trait_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_animal_personality_traits_animal_id_animals')),
    sa.ForeignKeyConstraint(['personality_trait_id'], ['personality_traits.id'], name=op.f('fk_animal_personality_traits_personality_trait_id_personality_traits')),
    sa.PrimaryKeyConstraint('animal_id', 'personality_trait_id', name=op.f('pk_animal_personality_traits'))
    )
    op.create_table('animal_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_animal_photos_display_order_non_negative'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_animal_photos_animal_id_animals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_photos'))
    )
    op.create_index('uq_animal_photos_one_primary', 'animal_photos', ['animal_id'], unique=True, postgresql_where=sa.text('is_primary IS true'))
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adopter_profile_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'HOME_CHECK', 'APPROVED', 'ADOPTED', 'DECLINED', 'WITHDRAWN', 'CLOSED_ANIMAL_ADOPTED', name='application_status'), nullable=False),
    sa.Column('applicant_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adopter_profile_id'], ['adopter_profiles.id'], name=op.f('fk_applications_adopter_profile_id_adopter_profiles')),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_applications_animal_id_animals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_table('favourites',
    sa.Column('adopter_profile_id', sa.Uuid(), nullable=False),
    sa.Column('animal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['adopter_profile_id'], ['adopter_profiles.id'], name=op.f('fk_favourites_adopter_profile_id_adopter_profiles')),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_favourites_animal_id_animals')),
    sa.PrimaryKeyConstraint('adopter_profile_id', 'animal_id', name=op.f('pk_favourites'))
    )
    op.create_table('application_child_age_groups',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('child_age_group', sa.Enum('YOUNG_CHILDREN', 'SCHOOL_AGE_CHILDREN', 'TEENAGERS', name='child_age_group'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_child_age_groups_application_id_applications')),
    sa.PrimaryKeyConstraint('application_id', 'child_age_group', name=op.f('pk_application_child_age_groups'))
    )
    op.create_table('application_preferred_sizes',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='size'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_preferred_sizes_application_id_applications')),
    sa.PrimaryKeyConstraint('application_id', 'size', name=op.f('pk_application_preferred_sizes'))
    )
    op.create_table('application_preferred_species',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', name='species'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_preferred_species_application_id_applications')),
    sa.PrimaryKeyConstraint('application_id', 'species', name=op.f('pk_application_preferred_species'))
    )
    op.create_table('application_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'HOME_CHECK', 'APPROVED', 'ADOPTED', 'DECLINED', 'WITHDRAWN', 'CLOSED_ANIMAL_ADOPTED', name='application_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_status_history_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_status_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_status_history')
    op.drop_table('application_preferred_species')
    op.drop_table('application_preferred_sizes')
    op.drop_table('application_child_age_groups')
    op.drop_table('favourites')
    op.drop_table('applications')
    op.drop_index('uq_animal_photos_one_primary', table_name='animal_photos', postgresql_where=sa.text('is_primary IS true'))
    op.drop_table('animal_photos')
    op.drop_table('animal_personality_traits')
    op.drop_table('adopter_preferred_species')
    op.drop_table('adopter_preferred_sizes')
    op.drop_table('adopter_child_age_groups')
    op.drop_table('animals')
    op.drop_table('adopter_profiles')
    op.drop_table('users')
    op.drop_table('organisation_invitations')
    op.drop_table('facilities')
    op.drop_table('rescue_organisations')
    op.drop_table('personality_traits')
    # ### end Alembic commands ###
